apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-animal-adoption
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-animal-adoption
  template:
    metadata:
      labels:
        app: api-animal-adoption
    spec:
      containers:
        - name: api-animal-adoption
          image: localhost/api_animal_adoption:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/animal_adoption
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: 123ateo9
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: https://keycloak.animal-adoption.com.br:8443/realms/ANIMAL_ADOPTION
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.5"
            requests:
              memory: "256Mi"
              cpu: "0.25"
---
apiVersion: v1
kind: Service
metadata:
  name: api-animal-adoption
spec:
  type: NodePort
  selector:
    app: api-animal-adoption
  ports:
    - port: 8081
      nodePort: 31081
