services:
  api_animal_adoption:
    build: .
    container_name: api_animal_adoption
    restart: unless-stopped

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/animal_adoption
      SPRING_DATASOURCE_USERNAME: desenv
      SPRING_DATASOURCE_PASSWORD: 123ateo9
      SPRING_PROFILES_ACTIVE: docker
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://auth.animal-adoption.com.br/realms/MY_KEYCLOAK

    networks:
      - my-infra-docker

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.api-animal-adoption.rule=Host(`api.animal-adoption.com.br`)"
      - "traefik.http.routers.api-animal-adoption.entrypoints=websecure"
      - "traefik.http.routers.api-animal-adoption.tls=true"
      - "traefik.http.routers.api-animal-adoption.tls.certresolver=letsencrypt"

      - "traefik.http.services.api-animal-adoption.loadbalancer.server.port=8083"

networks:
  my-infra-docker:
    external: true