services:
  api_animal_adoption:
    build: .
    container_name: api_animal_adoption
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/animal_adoption
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123atexxo9
      SPRING_PROFILES_ACTIVE: docker
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak.animal-adoption.com.br:8080/realms/MY_KEYCLOAK
    extra_hosts:
      - "keycloak.animal-adoption.com.br:192.168.18.7"
    networks:
      - my-infra-docker
networks:
  my-infra-docker:
    external: true